#!/bin/sh
if grep -q 'heddle_prepare=1' /proc/cmdline; then
  if [ -c /dev/ttyAMA0 ]; then
    exec > /dev/ttyAMA0 2>&1
  else
    exec > /dev/ttyS0 2>&1
  fi
else
  exec 2>&1
fi
set -e

# start docker
sv start docker

# check docker is ready
docker info
docker history scratch

# check if weave images exist
if docker history weaveworks/weave && \
   docker history weaveworks/weavedns && \
   docker history weaveworks/weaveexec; then
  echo weave images exist
  exec sv down prepare_weave
fi

# make weave images
cd "$GOPATH/src/github.com/weaveworks/weave"
docker load -i alpine.tar
CGO_CPPFLAGS="$CPPFLAGS" CGO_LDFLAGS="$LDFLAGS" make SUDO=
rm -f *.tar weaveexec/*.tgz
# we'll be restarted and check for the images again
